# Generated by Django 3.0.5 on 2020-04-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200411_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='my_answer',
            new_name='user_answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='my_answer_importance',
            new_name='user_importance_level',
        ),
    ]
