# Generated by Django 3.0.5 on 2020-04-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200412_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='other_user_importance',
            new_name='other_user_importance_level',
        ),
    ]
