# Generated by Django 3.0.5 on 2020-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200412_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='other_user_points',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_answer_points',
            field=models.IntegerField(default=-1),
        ),
    ]
