# Generated by Django 3.0.5 on 2020-04-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='gander',
            new_name='gender',
        ),
    ]
