# Generated by Django 3.0.5 on 2020-04-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200411_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
