# Generated by Django 3.0.5 on 2020-04-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_has_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='has_profile',
            new_name='hasProfile',
        ),
    ]
