# Generated by Django 3.0.5 on 2020-04-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0002_auto_20200416_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flagged',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
